services:
  subana:
    build: .
    container_name: subana
    restart: unless-stopped
    ports:
      - "8501:8080"
    volumes:
      - /Users/xiao/Web/subana:/app/data
      - /Volumes/Drive/data/media:/media
    environment:
      - TZ=Asia/Taipei
      - PYTHONUNBUFFERED=1
  
  # jellyfin:
  #   image: jellyfin/jellyfin:latest
  #   container_name: jellyfin
  #   user: 501:20
  #   ports:
  #     - 8096:8096
  #   volumes:
  #     - /Users/xiao/Web/jellyfin/config:/config
  #     - /Users/xiao/Web/jellyfin/cache:/cache
  #     - /Volumes/Drive/data/media:/data/media
  #   restart: 'always'
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'