services:
  subana:
    build: .
    container_name: subana
    restart: unless-stopped
    ports:
      - "8501:8080"
    volumes:
      - /Users/xiao/Web/subana:/app/data
      - /Volumes/Drive/data/media:/media
    environment:
      - TZ=Asia/Taipei
      - PYTHONUNBUFFERED=1
